### ISSUE TITLE
Team David Zilberman Code Review

### ISSUE THREAD

**Issue by LogsC** [tamjidarko/EEP_153_Project_4#1]
Hi, I noticed that the GitHub repository linked in Eli's post (https://github.com/vivfeng/EEP_153_Project_4) appears to be a fork of this repository (https://github.com/tamjidarko/EEP_153_Project_4), which I presume is the correct link as it was updated more recently and is the link present in your team's code post yesterday. It might be helpful to clarify this, as the two repositories seem to contain different code. I liked the code and was able to run it without errors! I saw that there was also an html file and am wondering what the purpose of that file is.

**Comment by hoshiaip** [comment]
Hi, thank you for noticing the wrong link in Eli's post and for your review! The html file is just for people to see the results without having to run the code themselves.
